; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32cam]
;platform = espressif32
platform = espressif32@6.5.0
board = esp32cam
framework = arduino
;platform_packages = 
	;framework-arduinoespressif32 @ 3.10006.210326
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0

upload_protocol = espota
upload_port = camera.local
;upload_port = 192.168.0.30
;upload_port = 192.168.0.71
;upload_port = COM7

;monitor_port = COM7
;monitor_port = COM3

;board_build.partitions = partitions_custom.csv

;build_src_filter = +<OTA.cpp>
build_src_filter = +<cam_mDNS.cpp>

;lib_extra_dirs = ~/Documents/Arduino/libraries

;build_flags = 
	;-D PIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS
	;-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO

lib_deps = 
	links2004/WebSockets@^2.6.0
	bblanchon/ArduinoJson@^7.1.0
	https://github.com/me-no-dev/ESPAsyncWebServer.git


	

