; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
board = esp32dev
platform = espressif32@6.5.0
framework = arduino

build_src_filter  = +<teles_AP.cpp> +<IRController.cpp>;

monitor_filters = esp32_exception_decoder
monitor_speed = 115200
;monitor_rts = 0
;monitor_dtr = 0

upload_protocol = espota
upload_port = 192.168.4.1

;upload_port = COM4
;upload_port = COM3
;monitor_port = COM4
;monitor_port = COM3
board_build.partitions = partitions_custom.csv


;upload_flags = 
;    --timeout=30
board_build.filesystem = littlefs

;build_flags =
 ;   -DDEBUG_ESP_HTTP_CLIENT
  ;  -DDEBUG_ESP_PORT=Serial

;upload_flags = 
;    --timeout=30

;build_flags = 
;    -Wall -Wextra

build_flags =     
    -Wall
    -Wextra
    -Wunused-variable   ; variablre non utilisée
	;-Wunused-function   ; fonction non utilisée

;build_flags = -O0 -g -fstack-protector-all
					;monitor_filters = default, esp32_exception_decoder

					;build_flags = 
						;-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE

;build_flags = -DCORE_DEBUG_LEVEL=5
 ;   -Os
 ;   -ffunction-sections
 ;   -fdata-sections
 ;   -Wl,--gc-sections
 ;   -DDEBUG=0


lib_deps = 
	bodmer/TFT_eFEX@^0.0.8
	bodmer/TFT_eSPI@^2.5.43
	bodmer/JPEGDecoder@^2.0.0
	bblanchon/ArduinoJson@^6.21.3
	gin66/FastAccelStepper@^0.30.14
	davidarmstrong/SiderealPlanets@^1.4.0
	ESP32Async/ESPAsyncWebServer@3.6.0
	diyables/DIYables_IRcontroller@^1.0.0
	WebSockets@^2.4.1



	
