; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32dev]
;platform = espressif32
platform = espressif32@6.5.0
board = esp32dev
framework = arduino

; Spécifier le modèle de caméra et activer le PSRAM
build_flags =
   -D CAMERA_MODEL_AI_THINKER
   -D BOARD_HAS_PSRAM
   -mfix-esp32-psram-cache-issue

; S'assurer que la table de partitionnement offre suffisamment d'espace
board_build.partitions = huge_app.csv	

monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0

upload_protocol = espota
upload_port = 192.168.4.10
;upload_port = COM6

monitor_port = COM6
;monitor_port = COM3

;build_src_filter = +<OTA.cpp>
build_src_filter = +<cam_adr_10.cpp>

lib_deps = 
	links2004/WebSockets@^2.6.0
	bblanchon/ArduinoJson@^7.1.0
	ESP32Async/ESPAsyncWebServer@3.6.0


	

